version: '3.8'

services:
  reddit-gallery:
    build: .
    container_name: reddit-gallery
    image: dhovin/reddit-gallery:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
      - PUID=99          # Map host user UID for unRaid permission mapping (nobody)
      - PGID=100         # Map host group GID (users)
      - CACHE_LIMIT_GB=2 # Max local media cache limit in Gigabytes
      - NODE_ENV=production
